# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: joomla

# The type of the application to build.
type: php:5.6

build:
    flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: ""
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"

        "/administrator":
            root: "administrator"
            passthru: "/administrator/index.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    '/cache':
        source: local
        source_path: cache
    '/components':
        source: local
        source_path: components
    '/tmp':
        source: local
        source_path: tmp
    '/libraries':
        source: local
        source_path: libraries
    '/media':
        source: local
        source_path: media
    '/modules':
        source: local
        source_path: modules
    '/language':
        source: local
        source_path: language
    '/plugins':
        source: local
        source_path: plugins
    '/administrator/logs':
        source: local
        source_path: admin-logs
    '/administrator/cache':
        source: local
        source_path: admin-cache
    '/administrator/components':
        source: local
        source_path: admin-components
    '/administrator/language':
        source: local
        source_path: admin-language
    '/administrator/manifests':
        source: local
        source_path: admin-manifests

hooks:
    deploy: |
        set -e
        if test ! -f administrator/logs/installed.lock ; then
            rsync -a init/admin-cache/ administrator/cache/
            rsync -a init/admin-components/ administrator/components/
            rsync -a init/admin-logs/ administrator/logs/
            rsync -a init/admin-language/ administrator/language/
            rsync -a init/admin-manifests/ administrator/manifests/
            rsync -a init/cache/ cache/
            rsync -a init/components/ components/
            rsync -a init/tmp/ tmp/
            rsync -a init/libraries/ libraries/
            rsync -a init/media/ media/
            rsync -a init/modules/ modules/
            rsync -a init/language/ language/
            rsync -a init/plugins/ plugins/
            mysql -h database.internal -P 3306 -u user main < joomla-init.sql
            mysql -h database.internal -u user -e "INSERT  INTO joo_users (name, username, password, params) VALUES ('Administrator', '${ADMIN_LOGIN}', md5('${ADMIN_PASSWORD}'), ''); INSERT INTO joo_user_usergroup_map (user_id,group_id) VALUES (LAST_INSERT_ID(),'8');" main
            cd && touch administrator/logs/installed.lock
        fi
