"https://{default}/":
    type: upstream
    upstream: "joomla:php"
"http://{default}/":
    type: redirect
    to: "https://{default}/"
"https://www.{default}/":
   type: redirect
   to: "https://{default}/"